export const CatList = [
  { value: 'korean', label: '세상에 하나뿐인 코숏' },
  { value: 'russian-blue', label: '러시안 블루' },
  { value: 'persian', label: '페르시안' },
  { value: 'siamese', label: '샴' },
  { value: 'turkish-angora', label: '터키쉬 앙고라' },
  { value: 'abyssinian', label: '아비시니안' },
  { value: 'american-shorthair', label: '아메리칸 숏헤어' },
  { value: 'norwegian-forest', label: '노르웨이 숲' },
  { value: 'ragdoll', label: '랙돌' },
  { value: 'scottish-fold', label: '스코티시 폴드' },
  { value: 'bengal', label: '뱅갈' },
  { value: 'maine-coon', label: '메인 쿤' },
  { value: 'sphynx', label: '스핑크스' },
  { value: 'british-shorthair', label: '브리티쉬 숏헤어' },
  { value: 'birman', label: '버만' },
  { value: 'oriental-shorthair', label: '오리엔탈 숏헤어' },
  { value: 'egyptian-mau', label: '이집션 마우' },
  { value: 'devon-rex', label: '데본 렉스' },
  { value: 'cornish-rex', label: '코니시 렉스' },
  { value: 'himalayan', label: '히말라얀' },
  { value: 'savannah', label: '서배너' },
  { value: 'balinese', label: '발리네즈' },
  { value: 'tonkinese', label: '통키니즈' },
  { value: 'manx', label: '맨스' },
  { value: 'singapura', label: '싱가푸라' },
  { value: 'japanese-bobtail', label: '재패니즈 밥테일' },
  { value: 'selkirk-rex', label: '셀커크 렉스' },
  { value: 'somali', label: '소말리' },
  { value: 'la-perm', label: '라펌' },
  { value: 'burmese', label: '버미즈' },
  { value: 'exotic-shorthair', label: '엑조틱 숏헤어' },
  { value: 'chartreux', label: '샤트룩스' },
  { value: 'ocicat', label: '오시캣' },
  { value: 'turkish-van', label: '터키쉬 반' },
];

export const DogList = [
  { value: 'unique-mix', label: '세상에 하나뿐인 믹스' },
  { value: 'korean-jindo', label: '진돗개' },
  { value: 'golden-retriever', label: '골든 리트리버' },
  { value: 'labrador-retriever', label: '래브라도 리트리버' },
  { value: 'poodle', label: '푸들' },
  { value: 'bulldog', label: '불독' },
  { value: 'beagle', label: '비글' },
  { value: 'shih-tzu', label: '시츄' },
  { value: 'pomeranian', label: '포메라니안' },
  { value: 'dachshund', label: '닥스훈트' },
  { value: 'corgi', label: '웰시 코기' },
  { value: 'chihuahua', label: '치와와' },
  { value: 'siberian-husky', label: '시베리안 허스키' },
  { value: 'shiba-inu', label: '시바견' },
  { value: 'samoyed', label: '사모예드' },
  { value: 'yorkshire-terrier', label: '요크셔 테리어' },
  { value: 'maltese', label: '말티즈' },
  { value: 'bichon-frise', label: '비숑 프리제' },
  { value: 'border-collie', label: '보더 콜리' },
  { value: 'pug', label: '퍼그' },
  { value: 'rottweiler', label: '로트와일러' },
  { value: 'boxer', label: '복서' },
  { value: 'maltipoo', label: '말티푸' },
  { value: 'unique-mix', label: '세상에 하나뿐인 믹스' },
  { value: 'dalmatian', label: '달마시안' },
  { value: 'great-dane', label: '그레이트 데인' },
  { value: 'bernese-mountain-dog', label: '버니즈 마운틴 도그' },
  { value: 'australian-shepherd', label: '오스트레일리언 셰퍼드' },
  { value: 'cavalier-king-charles-spaniel', label: '킹 찰스 스패니얼' },
  { value: 'akita', label: '아키타견' },
  { value: 'miniature-schnauzer', label: '미니어처 슈나우저' },
  { value: 'alaskan-malamute', label: '알래스칸 말라뮤트' },
  { value: 'st-bernard', label: '세인트 버나드' },
  { value: 'english-cocker-spaniel', label: '잉글리시 코커 스패니얼' },
  { value: 'greyhound', label: '그레이하운드' },
  { value: 'boston-terrier', label: '보스턴 테리어' },
  { value: 'bull-terrier', label: '불 테리어' },
  { value: 'jack-russell-terrier', label: '잭 러셀 테리어' },
  { value: 'australian-cattle-dog', label: '오스트레일리언 캐틀 독' },
  { value: 'american-pit-bull-terrier', label: '아메리칸 핏불 테리어' },
  { value: 'papillon', label: '빠삐용' },
  { value: 'sheltie', label: '셸티' },
  { value: 'american-eskimo-dog', label: '아메리칸 에스키모 도그' },
  { value: 'irish-setter', label: '아이리시 세터' },
  { value: 'bloodhound', label: '블러드하운드' },
  { value: 'newfoundland', label: '뉴펀들랜드' },
  { value: 'belgian-malinois', label: '벨지안 말리노이즈' },
  { value: 'weimaraner', label: '와이머라너' },
  { value: 'whippet', label: '휘핏' },
  { value: 'cane-corso', label: '카네 코르소' },
];
