export const CatList = [
  { value: '세상에 하나뿐인 코숏', label: '세상에 하나뿐인 코숏' },
  { value: '러시안 블루', label: '러시안 블루' },
  { value: '페르시안', label: '페르시안' },
  { value: '샴', label: '샴' },
  { value: '터키쉬 앙고라', label: '터키쉬 앙고라' },
  { value: '아비시니안', label: '아비시니안' },
  { value: '아메리칸 숏헤어', label: '아메리칸 숏헤어' },
  { value: '노르웨이 숲', label: '노르웨이 숲' },
  { value: '랙돌', label: '랙돌' },
  { value: '스코티시 폴드', label: '스코티시 폴드' },
  { value: '뱅갈', label: '뱅갈' },
  { value: '메인 쿤', label: '메인 쿤' },
  { value: '스핑크스', label: '스핑크스' },
  { value: '브리티쉬 숏헤어', label: '브리티쉬 숏헤어' },
  { value: '버만', label: '버만' },
  { value: '오리엔탈 숏헤어', label: '오리엔탈 숏헤어' },
  { value: '이집션 마우', label: '이집션 마우' },
  { value: '데본 렉스', label: '데본 렉스' },
  { value: '코니시 렉스', label: '코니시 렉스' },
  { value: '히말라얀', label: '히말라얀' },
  { value: '서배너', label: '서배너' },
  { value: '발리네즈', label: '발리네즈' },
  { value: '통키니즈', label: '통키니즈' },
  { value: '맨스', label: '맨스' },
  { value: '싱가푸라', label: '싱가푸라' },
  { value: '재패니즈 밥테일', label: '재패니즈 밥테일' },
  { value: '셀커크 렉스', label: '셀커크 렉스' },
  { value: '소말리', label: '소말리' },
  { value: '라펌', label: '라펌' },
  { value: '버미즈', label: '버미즈' },
  { value: '엑조틱 숏헤어', label: '엑조틱 숏헤어' },
  { value: '샤트룩스', label: '샤트룩스' },
  { value: '오시캣', label: '오시캣' },
  { value: '터키쉬 반', label: '터키쉬 반' },
];

export const DogList = [
  { value: '세상에 하나뿐인 믹스', label: '세상에 하나뿐인 믹스' },
  { value: '진돗개', label: '진돗개' },
  { value: '골든 리트리버', label: '골든 리트리버' },
  { value: '래브라도 리트리버', label: '래브라도 리트리버' },
  { value: '푸들', label: '푸들' },
  { value: '불독', label: '불독' },
  { value: '비글', label: '비글' },
  { value: '시츄', label: '시츄' },
  { value: '포메라니안', label: '포메라니안' },
  { value: '닥스훈트', label: '닥스훈트' },
  { value: '웰시 코기', label: '웰시 코기' },
  { value: '치와와', label: '치와와' },
  { value: '시베리안 허스키', label: '시베리안 허스키' },
  { value: '시바견', label: '시바견' },
  { value: '사모예드', label: '사모예드' },
  { value: '요크셔 테리어', label: '요크셔 테리어' },
  { value: '말티즈', label: '말티즈' },
  { value: '비숑 프리제', label: '비숑 프리제' },
  { value: '보더 콜리', label: '보더 콜리' },
  { value: '퍼그', label: '퍼그' },
  { value: '로트와일러', label: '로트와일러' },
  { value: '복서', label: '복서' },
  { value: '말티푸', label: '말티푸' },
  { value: '세상에 하나뿐인 믹스', label: '세상에 하나뿐인 믹스' },
  { value: '달마시안', label: '달마시안' },
  { value: '그레이트 데인', label: '그레이트 데인' },
  { value: '버니즈 마운틴 도그', label: '버니즈 마운틴 도그' },
  { value: '오스트레일리언 셰퍼드', label: '오스트레일리언 셰퍼드' },
  { value: '킹 찰스 스패니얼', label: '킹 찰스 스패니얼' },
  { value: '아키타견', label: '아키타견' },
  { value: '미니어처 슈나우저', label: '미니어처 슈나우저' },
  { value: '알래스칸 말라뮤트', label: '알래스칸 말라뮤트' },
  { value: '세인트 버나드', label: '세인트 버나드' },
  { value: '잉글리시 코커 스패니얼', label: '잉글리시 코커 스패니얼' },
  { value: '그레이하운드', label: '그레이하운드' },
  { value: '보스턴 테리어', label: '보스턴 테리어' },
  { value: '불 테리어', label: '불 테리어' },
  { value: '잭 러셀 테리어', label: '잭 러셀 테리어' },
  { value: '오스트레일리언 캐틀 독', label: '오스트레일리언 캐틀 독' },
  { value: '아메리칸 핏불 테리어', label: '아메리칸 핏불 테리어' },
  { value: '빠삐용', label: '빠삐용' },
  { value: '셸티', label: '셸티' },
  { value: '아메리칸 에스키모 도그', label: '아메리칸 에스키모 도그' },
  { value: '아이리시 세터', label: '아이리시 세터' },
  { value: '블러드하운드', label: '블러드하운드' },
  { value: '뉴펀들랜드', label: '뉴펀들랜드' },
  { value: '벨지안 말리노이즈', label: '벨지안 말리노이즈' },
  { value: '와이머라너', label: '와이머라너' },
  { value: '휘핏', label: '휘핏' },
  { value: '카네 코르소', label: '카네 코르소' },
];
