export const CatList = [
  { value: 'korean', label: '세상에 하나뿐인 코숏' },
  { value: 'russian-blue', label: '러시안 블루' },
  { value: 'persian', label: '페르시안' },
  { value: 'siamese', label: '샴' },
  { value: 'turkish-angora', label: '터키쉬 앙고라' },
  { value: 'abyssinian', label: '아비시니안' },
  { value: 'american-shorthair', label: '아메리칸 숏헤어' },
  { value: 'norwegian-forest', label: '노르웨이 숲' },
  { value: 'ragdoll', label: '랙돌' },
  { value: 'scottish-fold', label: '스코티시 폴드' },
  { value: 'bengal', label: '뱅갈' },
  { value: 'maine-coon', label: '메인 쿤' },
  { value: 'sphynx', label: '스핑크스' },
  { value: 'british-shorthair', label: '브리티쉬 숏헤어' },
];

export const DogList = [
  { value: 'korean-jindo', label: '진돗개' },
  { value: 'golden-retriever', label: '골든 리트리버' },
  { value: 'labrador-retriever', label: '래브라도 리트리버' },
  { value: 'poodle', label: '푸들' },
  { value: 'bulldog', label: '불독' },
  { value: 'beagle', label: '비글' },
  { value: 'shih-tzu', label: '시츄' },
  { value: 'pomeranian', label: '포메라니안' },
  { value: 'dachshund', label: '닥스훈트' },
  { value: 'corgi', label: '웰시 코기' },
  { value: 'chihuahua', label: '치와와' },
  { value: 'siberian-husky', label: '시베리안 허스키' },
  { value: 'shiba-inu', label: '시바견' },
  { value: 'samoyed', label: '사모예드' },
  { value: 'yorkshire-terrier', label: '요크셔 테리어' },
  { value: 'maltese', label: '말티즈' },
  { value: 'bichon-frise', label: '비숑 프리제' },
  { value: 'border-collie', label: '보더 콜리' },
  { value: 'pug', label: '퍼그' },
  { value: 'rottweiler', label: '로트와일러' },
  { value: 'boxer', label: '복서' },
  { value: 'maltipoo', label: '말티푸' },
  { value: 'unique-mix', label: '세상에 하나뿐인 믹스' },
];
